###############################################################################
#
# Blueprint for Health Insurance Portability and Accountability Act (HIPAA)
#
# Profile Description:
# The HIPAA Security Rule establishes U.S. national standards to protect individuals’
# electronic personal health information that is created, received, used, or
# maintained by a covered entity. The Security Rule requires appropriate
# administrative, physical and technical safeguards to ensure the
# confidentiality, integrity, and security of electronic protected health
# information.
# This profile configures Red Hat Enterprise Linux 8 to the HIPAA Security
# Rule identified for securing of electronic protected health information.
# Use of this profile in no way guarantees or makes claims against legal compliance against the HIPAA Security Rule(s).
#
# Profile ID:  xccdf_org.ssgproject.content_profile_hipaa
# Benchmark ID:  xccdf_org.ssgproject.content_benchmark_RHEL-8
# Benchmark Version:  0.1.72
# XCCDF Version:  1.2
#
# This file was generated by OpenSCAP 1.3.10 using:
# $ oscap xccdf generate fix --profile xccdf_org.ssgproject.content_profile_hipaa --fix-type blueprint xccdf-file.xml
#
# This Blueprint is generated from an OpenSCAP profile without preliminary evaluation.
# It attempts to fix every selected rule, even if the system is already compliant.
#
# How to apply this Blueprint:
# composer-cli blueprints push blueprint.toml
#
###############################################################################

name = "hardened_xccdf_org.ssgproject.content_profile_hipaa"
description = "Health Insurance Portability and Accountability Act (HIPAA)"
version = "0.1.72"

[customizations.openscap]
profile_id = "xccdf_org.ssgproject.content_profile_hipaa"
# If your hardening data stream is not part of the 'scap-security-guide' package
# provide the absolute path to it (from the root of the image filesystem).
# datastream = "/usr/share/xml/scap/ssg/content/ssg-xxxxx-ds.xml"


[customizations.kernel]
append = "audit=1"

[customizations.services]
enabled = ["crond","auditd"]
disabled = ["zebra","telnet","rlogin","rexec","xinetd","kdump","autofs","debug-shell"]
masked = []
