###############################################################################
#
# Blueprint for DISA STIG with GUI for Red Hat Enterprise Linux 8
#
# Profile Description:
# This profile contains configuration checks that align to the
# DISA STIG with GUI for Red Hat Enterprise Linux 8 V1R13.
# In addition to being applicable to Red Hat Enterprise Linux 8, DISA recognizes this
# configuration baseline as applicable to the operating system tier of
# Red Hat technologies that are based on Red Hat Enterprise Linux 8, such as:
# - Red Hat Enterprise Linux Server
# - Red Hat Enterprise Linux Workstation and Desktop
# - Red Hat Enterprise Linux for HPC
# - Red Hat Storage
# - Red Hat Containers with a Red Hat Enterprise Linux 8 image
# Warning: The installation and use of a Graphical User Interface (GUI)
# increases your attack vector and decreases your overall security posture. If
# your Information Systems Security Officer (ISSO) lacks a documented operational
# requirement for a graphical user interface, please consider using the
# standard DISA STIG for Red Hat Enterprise Linux 8 profile.
#
# Profile ID:  xccdf_org.ssgproject.content_profile_stig_gui
# Benchmark ID:  xccdf_org.ssgproject.content_benchmark_RHEL-8
# Benchmark Version:  0.1.72
# XCCDF Version:  1.2
#
# This file was generated by OpenSCAP 1.3.10 using:
# $ oscap xccdf generate fix --profile xccdf_org.ssgproject.content_profile_stig_gui --fix-type blueprint xccdf-file.xml
#
# This Blueprint is generated from an OpenSCAP profile without preliminary evaluation.
# It attempts to fix every selected rule, even if the system is already compliant.
#
# How to apply this Blueprint:
# composer-cli blueprints push blueprint.toml
#
###############################################################################

name = "hardened_xccdf_org.ssgproject.content_profile_stig_gui"
description = "DISA STIG with GUI for Red Hat Enterprise Linux 8"
version = "0.1.72"

[customizations.openscap]
profile_id = "xccdf_org.ssgproject.content_profile_stig_gui"
# If your hardening data stream is not part of the 'scap-security-guide' package
# provide the absolute path to it (from the root of the image filesystem).
# datastream = "/usr/share/xml/scap/ssg/content/ssg-xxxxx-ds.xml"


[[packages]]
name = "aide"
version = "*"

[customizations]
fips = true

[[customizations.filesystem]]
mountpoint = "/home"
size = 1073741824

[[customizations.filesystem]]
mountpoint = "/tmp"
size = 1073741824

[[customizations.filesystem]]
mountpoint = "/var"
size = 3221225472

[[customizations.filesystem]]
mountpoint = "/var/log"
size = 5368709120

[[customizations.filesystem]]
mountpoint = "/var/log/audit"
size = 10737418240

[[customizations.filesystem]]
mountpoint = "/var/tmp"
size = 1073741824

[[packages]]
name = "rng-tools"
version = "*"

[[packages]]
name = "tmux"
version = "*"

[[packages]]
name = "opensc"
version = "*"

[[packages]]
name = "openssl-pkcs11"
version = "*"

[[packages]]
name = "audit"
version = "*"

[[packages]]
name = "rsyslog-gnutls"
version = "*"

[[packages]]
name = "rsyslog"
version = "*"

[[packages]]
name = "firewalld"
version = "*"

[[packages]]
name = "policycoreutils"
version = "*"

[[packages]]
name = "fapolicyd"
version = "*"

[[packages]]
name = "mailx"
version = "*"

[[packages]]
name = "postfix"
version = "*"

[[packages]]
name = "openssh-server"
version = "*"

[[packages]]
name = "usbguard"
version = "*"

[customizations.kernel]
append = "slub_debug=P page_poison=1 vsyscall=none pti=on audit_backlog_limit=8192 audit=1"

[customizations.services]
enabled = ["usbguard","sshd","rngd","fapolicyd","firewalld","rsyslog","auditd"]
disabled = ["kdump","autofs","debug-shell"]
masked = []
