# https://osbuild.org/docs/user-guide/blueprint-reference

version = '1.0.0'

name = 'RHEL-8-NIST-HIPAA'

# https://doi.org/10.6028/NIST.SP.800-66r2
description = '''
Red Hat Enterprise Linux (RHEL) 8
National Institute of Standards and Technology (NIST)
Implementing the Health Insurance Portability and Accountability Act (HIPAA) Security Rule (NIST 800-66)
Profile ID:  xccdf_org.ssgproject.content_profile_hipaa
Benchmark ID:  xccdf_org.ssgproject.content_benchmark_RHEL-8
'''

distro = 'rhel-8'

[customizations]
partitioning_mode = 'auto-lvm'

[customizations.kernel]
append = 'audit=1'

[customizations.openscap]
profile_id = 'xccdf_org.ssgproject.content_profile_hipaa'

[customizations.services]
enabled = ['crond', 'auditd']
disabled = ['zebra', 'telnet', 'rlogin', 'rexec', 'xinetd', 'kdump', 'autofs', 'debug-shell']
masked = []
