# https://osbuild.org/docs/user-guide/blueprint-reference

version = '1.0.0'

name = 'RHEL-8-NIST-PCI-DSS'

# http://doi.org/10.6028/NIST.SP.1800-16
description = '''
Red Hat Enterprise Linux (RHEL) 8
National Institute of Standards and Technology (NIST)
Payment Card Industry - Data Security Standard (PCI-DSS) (NIST 1800-16)
Profile ID:  xccdf_org.ssgproject.content_profile_pci-dss
Benchmark ID:  xccdf_org.ssgproject.content_benchmark_RHEL-8
'''

distro = 'rhel-8'

[customizations]
partitioning_mode = 'auto-lvm'

[customizations.kernel]
append = 'audit_backlog_limit=8192 audit=1'

[customizations.openscap]
profile_id = 'xccdf_org.ssgproject.content_profile_pci-dss'

[customizations.services]
enabled = ['firewalld', 'auditd']
disabled = ['rsyncd', 'rpcbind', 'avahi-daemon', 'nftables']
masked = []

[[packages]]
name = 'aide'
version = '*'

[[packages]]
name = 'audispd-plugins'
version = '*'

[[packages]]
name = 'audit'
version = '*'

[[packages]]
name = 'chrony'
version = '*'

[[packages]]
name = 'libselinux'
version = '*'

[[packages]]
name = 'logrotate'
version = '*'

[[packages]]
name = 'nftables'
version = '*'

[[packages]]
name = 'sudo'
version = '*'
