# https://osbuild.org/docs/user-guide/blueprint-reference

version = '1.0.0'

name = 'RHEL-9-DISA-STIG-GUI'

# https://public.cyber.mil/stigs
description = '''
Red Hat Enterprise Linux (RHEL) 9
Defense Information Systems Agency (DISA) Security Technical Implementation Guide (STIG) with GUI
Profile ID:  xccdf_org.ssgproject.content_profile_stig_gui
Benchmark ID:  xccdf_org.ssgproject.content_benchmark_RHEL-9
'''

distro = 'rhel-9'

[customizations]
partitioning_mode = 'auto-lvm'
fips = true

[customizations.kernel]
append = 'slub_debug=P page_poison=1 vsyscall=none pti=on audit_backlog_limit=8192 audit=1'

[customizations.openscap]
profile_id = 'xccdf_org.ssgproject.content_profile_stig_gui'

[customizations.services]
enabled = ['usbguard', 'sshd', 'chronyd', 'fapolicyd', 'firewalld', 'systemd-journald', 'rsyslog', 'auditd', 'pcscd']
disabled = ['kdump', 'debug-shell']
masked = []

[[customizations.filesystem]]
mountpoint = '/'
size = 3221225472

[[customizations.filesystem]]
mountpoint = '/boot'
size = 805306368

[[customizations.filesystem]]
mountpoint = '/home'
size = 1073741824

[[customizations.filesystem]]
mountpoint = '/tmp'
size = 1073741824

[[customizations.filesystem]]
mountpoint = '/var'
size = 2147483648

[[customizations.filesystem]]
mountpoint = '/var/log'
size = 1073741824

[[customizations.filesystem]]
mountpoint = '/var/log/audit'
size = 536870912

[[customizations.filesystem]]
mountpoint = '/var/tmp'
size = 536870912

[[packages]]
name = 'aide'
version = '*'

[[packages]]
name = 'audispd-plugins'
version = '*'

[[packages]]
name = 'audit'
version = '*'

[[packages]]
name = 'chrony'
version = '*'

[[packages]]
name = 'crypto-policies'
version = '*'

[[packages]]
name = 'fapolicyd'
version = '*'

[[packages]]
name = 'firewalld'
version = '*'

[[packages]]
name = 'gnutls-utils'
version = '*'

[[packages]]
name = 'libreswan'
version = '*'

[[packages]]
name = 'nss-tools'
version = '*'

[[packages]]
name = 'opensc'
version = '*'

[[packages]]
name = 'openssh-clients'
version = '*'

[[packages]]
name = 'openssh-server'
version = '*'

[[packages]]
name = 'openssl-pkcs11'
version = '*'

[[packages]]
name = 'pcsc-lite'
version = '*'

[[packages]]
name = 'policycoreutils'
version = '*'

[[packages]]
name = 'policycoreutils-python-utils'
version = '*'

[[packages]]
name = 'rng-tools'
version = '*'

[[packages]]
name = 'rsyslog'
version = '*'

[[packages]]
name = 'rsyslog-gnutls'
version = '*'

[[packages]]
name = 's-nail'
version = '*'

[[packages]]
name = 'subscription-manager'
version = '*'

[[packages]]
name = 'sudo'
version = '*'

[[packages]]
name = 'tmux'
version = '*'

[[packages]]
name = 'usbguard'
version = '*'
