# https://osbuild.org/docs/user-guide/blueprint-reference

version = '1.0.0'

name = 'RHEL-8-DISA-STIG-GUI'

# https://public.cyber.mil/stigs
description = '''
Red Hat Enterprise Linux (RHEL) 8
Defense Information Systems Agency (DISA) Security Technical Implementation Guide (STIG) with GUI
Profile ID:  xccdf_org.ssgproject.content_profile_stig_gui
Benchmark ID:  xccdf_org.ssgproject.content_benchmark_RHEL-8
'''

distro = 'rhel-8'

[customizations]
partitioning_mode = 'auto-lvm'
fips = true

[customizations.kernel]
append = 'slub_debug=P page_poison=1 vsyscall=none pti=on audit_backlog_limit=8192 audit=1'

[customizations.openscap]
profile_id = 'xccdf_org.ssgproject.content_profile_stig_gui'

[customizations.services]
enabled = ['usbguard', 'sshd', 'rngd', 'fapolicyd', 'firewalld', 'rsyslog', 'auditd']
disabled = ['kdump', 'autofs', 'debug-shell']
masked = []

[[customizations.filesystem]]
mountpoint = '/'
size = 3221225472

[[customizations.filesystem]]
mountpoint = '/boot'
size = 805306368

[[customizations.filesystem]]
mountpoint = '/home'
size = 1073741824

[[customizations.filesystem]]
mountpoint = '/tmp'
size = 1073741824

[[customizations.filesystem]]
mountpoint = '/var'
size = 2147483648

[[customizations.filesystem]]
mountpoint = '/var/log'
size = 1073741824

[[customizations.filesystem]]
mountpoint = '/var/log/audit'
size = 536870912

[[customizations.filesystem]]
mountpoint = '/var/tmp'
size = 536870912

[[packages]]
name = 'aide'
version = '*'

[[packages]]
name = 'audit'
version = '*'

[[packages]]
name = 'fapolicyd'
version = '*'

[[packages]]
name = 'firewalld'
version = '*'

[[packages]]
name = 'mailx'
version = '*'

[[packages]]
name = 'opensc'
version = '*'

[[packages]]
name = 'openssl-pkcs11'
version = '*'

[[packages]]
name = 'openssh-server'
version = '*'

[[packages]]
name = 'policycoreutils'
version = '*'

[[packages]]
name = 'postfix'
version = '*'

[[packages]]
name = 'rng-tools'
version = '*'

[[packages]]
name = 'rsyslog'
version = '*'

[[packages]]
name = 'rsyslog-gnutls'
version = '*'

[[packages]]
name = 'tmux'
version = '*'

[[packages]]
name = 'usbguard'
version = '*'
