###############################################################################
#
# Blueprint for DRAFT - Unclassified Information in Non-federal Information Systems and Organizations (NIST 800-171)
#
# Profile Description:
# From NIST 800-171, Section 2.2:
# Security requirements for protecting the confidentiality of CUI in nonfederal
# information systems and organizations have a well-defined structure that
# consists of:
# (i) a basic security requirements section;
# (ii) a derived security requirements section.
# The basic security requirements are obtained from FIPS Publication 200, which
# provides the high-level and fundamental security requirements for federal
# information and information systems. The derived security requirements, which
# supplement the basic security requirements, are taken from the security controls
# in NIST Special Publication 800-53.
# This profile configures Red Hat Enterprise Linux 9 to the NIST Special
# Publication 800-53 controls identified for securing Controlled Unclassified
# Information (CUI)."
#
# Profile ID:  xccdf_org.ssgproject.content_profile_cui
# Benchmark ID:  xccdf_org.ssgproject.content_benchmark_RHEL-9
# Benchmark Version:  0.1.72
# XCCDF Version:  1.2
#
# This file was generated by OpenSCAP 1.3.10 using:
# $ oscap xccdf generate fix --profile xccdf_org.ssgproject.content_profile_cui --fix-type blueprint xccdf-file.xml
#
# This Blueprint is generated from an OpenSCAP profile without preliminary evaluation.
# It attempts to fix every selected rule, even if the system is already compliant.
#
# How to apply this Blueprint:
# composer-cli blueprints push blueprint.toml
#
###############################################################################

name = "hardened_xccdf_org.ssgproject.content_profile_cui"
description = "DRAFT - Unclassified Information in Non-federal Information Systems and Organizations (NIST 800-171)"
version = "0.1.72"

[customizations.openscap]
profile_id = "xccdf_org.ssgproject.content_profile_cui"
# If your hardening data stream is not part of the 'scap-security-guide' package
# provide the absolute path to it (from the root of the image filesystem).
# datastream = "/usr/share/xml/scap/ssg/content/ssg-xxxxx-ds.xml"


[customizations]
fips = true

[[packages]]
name = "crypto-policies"
version = "*"

[[customizations.filesystem]]
mountpoint = "/var/log/audit"
size = 10737418240

[[packages]]
name = "sudo"
version = "*"

[[packages]]
name = "gnutls-utils"
version = "*"

[[packages]]
name = "openscap-scanner"
version = "*"

[[packages]]
name = "scap-security-guide"
version = "*"

[[packages]]
name = "subscription-manager"
version = "*"

[[packages]]
name = "dnf-automatic"
version = "*"

[[packages]]
name = "tmux"
version = "*"

[[packages]]
name = "audit"
version = "*"

[[packages]]
name = "firewalld"
version = "*"

[[packages]]
name = "fapolicyd"
version = "*"

[[packages]]
name = "chrony"
version = "*"

[[packages]]
name = "openssh-clients"
version = "*"

[[packages]]
name = "openssh-server"
version = "*"

[[packages]]
name = "usbguard"
version = "*"

[customizations.kernel]
append = "vsyscall=none page_alloc.shuffle=1 init_on_alloc=1 audit_backlog_limit=8192 audit=1"

[customizations.services]
enabled = ["usbguard","fapolicyd","firewalld","auditd"]
disabled = ["kdump","debug-shell"]
masked = []
